INSERT INTO Author (id,author_name,last_name) VALUES ('1','Rudyard',' Kipling');
INSERT INTO Author (id,author_name,last_name) VALUES ('2','Gabriel','García Márquez');
INSERT INTO Author (id,author_name,last_name) VALUES ('3','Eric','Freeman');
INSERT INTO Author (id,author_name,last_name) VALUES ('4','Elisabeth','Robson');
INSERT INTO Author (id,author_name,last_name) VALUES ('5','Kathy','Sierra');
INSERT INTO Book (id,name,editorial) VALUES ('1','Libro de la Selva','Macmillan Publishers');
INSERT INTO Book (id,name,editorial) VALUES ('2','100 años de Soledad','Editorial Sudamericana');
INSERT INTO Book (id,name,editorial) VALUES ('3','Head First Design Patterns','O''Reilly Media');
INSERT INTO book_author (book_id,author_id) VALUES (1,1);
INSERT INTO book_author (book_id,author_id) VALUES (2,2);
INSERT INTO book_author (book_id,author_id) VALUES (3,3);
INSERT INTO book_author (book_id,author_id) VALUES (3,4);
INSERT INTO book_author (book_id,author_id) VALUES (3,5);
